name: continuous integration

on: [push, pull_request]

jobs:
  build:
    name: Build mathlib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "::add-path::$HOME/.elan/bin"
          echo "::set-env name=short_lean_version::$(~/.elan/bin/lean --run scripts/lean_version.lean)"

      - name: compute lean file hash
        run: |
          lean_file_hash="$(echo `find src | grep '[.]lean$' | sort | xargs shasum` `shasum leanpkg.toml` "lean --version:" `lean --version` | shasum | head -c 40; echo)"
          echo "lean file hash: $lean_file_hash"
          echo "::set-env name=lean_file_hash::$lean_file_hash"
          echo `find src | grep '[.]lean$' | sort | xargs shasum`
          echo  `shasum leanpkg.toml`
          echo `lean --version`
          echo `shasum src/tactic/linarith.lean`
